import type { NextPage } from 'next'
import Head from 'next/head'
import { Brief } from '../components/Brief/Brief'
import { Header } from '../components/Header/Header'
import styles from '../styles/home.module.scss'

const briefMock = [
  {
    title: 'Título do depoimento',
    content: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    urlProfile: "",
    name: "Fulano de tal",
    date: "11/08/2022 às 15:03"
  }
]

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Header />

        <section className={styles.container}>
          <div className={styles.header}>
            <h2 className={styles.title}>Últimos depoimentos</h2>
            <button className={styles.buttonNewBrief}>Novo depoimento</button>
          </div>

          <div>
            {briefMock.map(brief => {
              return <Brief content={brief.content} date={brief.date} title={brief.title} urlProfile={brief.urlProfile} key={brief.title} />
            })}
          </div>
        </section>
        <footer>
        </footer>
      </main>
    </div>
  )
}

export default Home
